### Today Objectives:

* Introduction about ML
* Types of ML
* Workflow of ML
* overview of python,numpy and pandas

### Python:

In [7]:
# python keywords
# keyword is a predifined variable for doing specific tasks
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [8]:
# variables: variable is a name for stroing the value in memory location
a=10
print(a)

10


In [9]:
# data types:
# int, float, string,complex, bool, list,set,dict

a=10
b=20.4
c="string"
d=2+3j
e=True

print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))



<class 'int'>
<class 'float'>
<class 'str'>
<class 'complex'>
<class 'bool'>


In [11]:
# type conversions:
a='10'
type(a)

# convert into int
a='10'
b=int(a)
print(b,type(b))

10 <class 'int'>


In [13]:
# condtions statements
# if, else, elif, nested if
if(True):
    print("yes true")
else:
    print("no ")
    
    
if(False):
    print("yes true")
else:
    print("no ")

yes true
no 


In [14]:
a=10
if(a==100):
    print("if part",a)
elif(a==10):
    print("elif ",a)
else:
    print("else part",a)

elif  10


In [15]:
pin=12345
accname='niharika'
if(accname=='niharika'):
    if(pin==12345):
        print("valid user")
    else:
        print("invalid pin")
else:
    print("invalid username")

valid user


In [18]:
# loops:
# while and for loop

i=0
while(i<=10):
    print(i**2,end=" ")
    i=i+1



0 1 4 9 16 25 36 49 64 81 100 

In [19]:
for i in range(10):   # 0,9
    print(i,end=" ")
    

0 1 2 3 4 5 6 7 8 9 

In [22]:
# list:
# list is a collection of items. it is mutable data type
# list can be declare using [] and list method
l=list()
type(l)

l2=[]
type(l2)

l2=[1,2,3,4,5,True,2+3j,"string",23.34]
l2

[1, 2, 3, 4, 5, True, (2+3j), 'string', 23.34]

In [23]:
# read data from list using loops
l2=[1,2,3,4,5,True,2+3j,"string",23.34]
for i in l2:
    print(i,end=" ")

1 2 3 4 5 True (2+3j) string 23.34 

In [30]:
# slicing:
l2=[1,2,3,4,5,True,2+3j,"string",23.34]
l2[:4]
l2[4:6]
l2[-3:-1]
l2[::-1]
l2[0]=100
l2

[100, 2, 3, 4, 5, True, (2+3j), 'string', 23.34]

In [31]:
# tuple: it is like a list but it is a immutable data type
# tuple can be create using () and tuple()

t=(1,2,3,4,4,True,"string",2+3j,4.56)
t

(1, 2, 3, 4, 4, True, 'string', (2+3j), 4.56)

In [32]:
t[0]

1

In [33]:
t[0]=100

TypeError: 'tuple' object does not support item assignment

In [34]:
# set: it is like list without duplicates
# set is create using {data} and set()

s={1,2,3,2,4,4,5,5,6,7}
s

{1, 2, 3, 4, 5, 6, 7}

In [35]:
s[0]

TypeError: 'set' object is not subscriptable

In [36]:
#dictionary: it used for store the key value pair
d={1:10,2:30,4:60}
d

{1: 10, 2: 30, 4: 60}

In [39]:
d.keys()
d.values()
d.items()

dict_items([(1, 10), (2, 30), (4, 60)])

In [40]:
# functions:
def fun():
    print("python overview")
fun()


python overview


In [42]:
def fun(a,b):
    print("python overview",a,b)
fun(1,2)

python overview 1 2


In [43]:
# lambda: it is a annonimus function
a=lambda x:x
a(10)

10

In [44]:
a=lambda x:x**2
a(10)

100

In [45]:
# map
li=list(map(int,input().split()))
li

10 20 30 40 50


[10, 20, 30, 40, 50]

### numpy:

Numpy is python library for calculating data

In [46]:
l1=[1,2,3,4,5]
l2=[10,20,30,40,50]
l1+l2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [47]:
l1=[1,2,3,4,5]
l2=[10,20,30,40,50]
l1*l2

TypeError: can't multiply sequence by non-int of type 'list'

In [51]:
import numpy as np

l1=np.array([1,2,3,4,5,6])
l2=np.array([10,20,30,40,50,60])
l1+l2
l1*l2
l1-l2

array([ -9, -18, -27, -36, -45, -54])

In [55]:
l1=np.array([1,2,3,4,5,6,7,8],ndmin=2)
l1

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [56]:
l1=np.arange(10)
l1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
l1=np.eye(2)
l1

array([[1., 0.],
       [0., 1.]])

In [62]:
l1=np.eye(4,4)
l2=np.eye(4,4)
l1+l2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

### Pandas:

Pandas is a python library for working datasets

* series : 1d array
* Data Frame : 2d array


In [64]:
import pandas as pd
import numpy as np

s1=pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [65]:
d=pd.DataFrame([[10,20,30],[40,50,60],[70,80,90]])
d

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [66]:
d=pd.DataFrame([[10,20,30],[40,50,60],[70,80,90]])
d.columns=['first','second','thrid']
d

first  second  thrid
0     10      20     30
1     40      50     60
2     70      80     90

In [68]:
d={'sname':['a','b','c'],'sage':[10,20,30]}
df=pd.DataFrame(d)
df

sname  sage
0     a    10
1     b    20
2     c    30

In [69]:
df['sname']

0    a
1    b
2    c
Name: sname, dtype: object

In [70]:
df['sage']

0    10
1    20
2    30
Name: sage, dtype: int64